#!/usr/bin/env python3
#
# Copyright 2013 Andrej Antonov <polymorphm@gmail.com>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

assert str is not bytes

import unittest
from lib_torrent_proxy_patch_2013_09_16.test_bencode import TestBencode
from lib_torrent_proxy_patch_2013_09_16.test_bdecode import TestBdecode
from lib_torrent_proxy_patch_2013_09_16.test_url_patch import TestUrlPatch

if __name__ == '__main__':
    unittest.main()
